from enum import Enum


class DomainEvent(str, Enum):
    """Business events that execute synchronously after a successful transaction."""

    LEAD_CREATED = "LEAD_CREATED"
    LEAD_UPDATED = "LEAD_UPDATED"
    LEAD_ASSIGNED = "LEAD_ASSIGNED"
    LEAD_STATUS_CHANGED = "LEAD_STATUS_CHANGED"
    LEAD_WON = "LEAD_WON"
    LEAD_CONVERTED = "LEAD_CONVERTED"
    ACTIVITY_CREATED = "ACTIVITY_CREATED"
    FOLLOWUP_CREATED = "FOLLOWUP_CREATED"
    FOLLOWUP_COMPLETED = "FOLLOWUP_COMPLETED"

    PROPOSAL_CREATED = "PROPOSAL_CREATED"
    PROPOSAL_FINALIZED = "PROPOSAL_FINALIZED"

    BOOKING_CREATED = "BOOKING_CREATED"
    BOOKING_CONFIRMED = "BOOKING_CONFIRMED"
    BOOKING_CANCELLED = "BOOKING_CANCELLED"

    ADVANCE_RECEIVED = "ADVANCE_RECEIVED"
    PAYMENT_RECEIVED = "PAYMENT_RECEIVED"
    PAYMENT_VERIFIED = "PAYMENT_VERIFIED"
    EXPENSE_RECORDED = "EXPENSE_RECORDED"
    VENDOR_PAYMENT_RECORDED = "VENDOR_PAYMENT_RECORDED"
    REFUND_COMPLETED = "REFUND_COMPLETED"
    FINANCE_CLOSED = "FINANCE_CLOSED"

    TRIP_READY = "TRIP_READY"
    TRIP_STARTED = "TRIP_STARTED"
    TRIP_COMPLETED = "TRIP_COMPLETED"
    TRIP_CLOSED = "TRIP_CLOSED"
    TRIP_PLAN_CREATED = "TRIP_PLAN_CREATED"

    TASK_ASSIGNED = "TASK_ASSIGNED"
    TASK_COMPLETED = "TASK_COMPLETED"

    VENDOR_ALLOCATION_CONFIRMED = "VENDOR_ALLOCATION_CONFIRMED"
    VENDOR_ALLOCATION_LOCKED = "VENDOR_ALLOCATION_LOCKED"
    VENDOR_ALLOCATION_FAILED = "VENDOR_ALLOCATION_FAILED"
    CHECKLIST_COMPLETED = "CHECKLIST_COMPLETED"
    CHECKLIST_REOPENED = "CHECKLIST_REOPENED"


class ApplicationEvent(str, Enum):
    """Infrastructure events processed asynchronously."""

    EMAIL_REQUESTED = "EMAIL_REQUESTED"
    WHATSAPP_REQUESTED = "WHATSAPP_REQUESTED"
    IN_APP_NOTIFICATION_REQUESTED = "IN_APP_NOTIFICATION_REQUESTED"

    CACHE_INVALIDATED = "CACHE_INVALIDATED"

    AUDIT_LOG_REQUESTED = "AUDIT_LOG_REQUESTED"

    REPORT_GENERATION_REQUESTED = "REPORT_GENERATION_REQUESTED"

    FILE_UPLOAD_REQUESTED = "FILE_UPLOAD_REQUESTED"