from enum import Enum


class DomainEvent(str, Enum):
    """Business events that execute synchronously after a successful transaction."""

    LEAD_ASSIGNED = "LEAD_ASSIGNED"
    LEAD_WON = "LEAD_WON"

    PROPOSAL_CREATED = "PROPOSAL_CREATED"
    PROPOSAL_FINALIZED = "PROPOSAL_FINALIZED"

    BOOKING_CREATED = "BOOKING_CREATED"
    BOOKING_CONFIRMED = "BOOKING_CONFIRMED"
    BOOKING_CANCELLED = "BOOKING_CANCELLED"

    ADVANCE_RECEIVED = "ADVANCE_RECEIVED"
    PAYMENT_RECEIVED = "PAYMENT_RECEIVED"

    TRIP_READY = "TRIP_READY"
    TRIP_STARTED = "TRIP_STARTED"
    TRIP_COMPLETED = "TRIP_COMPLETED"

    TASK_ASSIGNED = "TASK_ASSIGNED"
    TASK_COMPLETED = "TASK_COMPLETED"


class ApplicationEvent(str, Enum):
    """Infrastructure events processed asynchronously."""

    EMAIL_REQUESTED = "EMAIL_REQUESTED"
    WHATSAPP_REQUESTED = "WHATSAPP_REQUESTED"
    IN_APP_NOTIFICATION_REQUESTED = "IN_APP_NOTIFICATION_REQUESTED"

    CACHE_INVALIDATED = "CACHE_INVALIDATED"

    AUDIT_LOG_REQUESTED = "AUDIT_LOG_REQUESTED"

    REPORT_GENERATION_REQUESTED = "REPORT_GENERATION_REQUESTED"

    FILE_UPLOAD_REQUESTED = "FILE_UPLOAD_REQUESTED"