"""add city master table

Revision ID: 22009dc619c2
Revises: bfea68e7409a
Create Date: 2026-07-30 22:42:10.728626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22009dc619c2'
down_revision = 'bfea68e7409a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('state_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'state_id', name='uq_city_code_state')
    )
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cities_is_active'), ['is_active'], unique=False)
        batch_op.create_index('ix_cities_state_id', ['state_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_index('ix_cities_state_id')
        batch_op.drop_index(batch_op.f('ix_cities_is_active'))

    op.drop_table('cities')
    # ### end Alembic commands ###
