"""add countries table with phone_code

Revision ID: 941b60de6673
Revises: ba379503a783
Create Date: 2026-07-26 16:34:08.225805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '941b60de6673'
down_revision = 'ba379503a783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dummy')
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.alter_column('phone_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('display_order',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.alter_column('display_order',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('phone_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    op.create_table('dummy',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
