"""add district master

Revision ID: a5161a840139
Revises: f98e7ca98a42
Create Date: 2026-07-26 17:42:00.428306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5161a840139'
down_revision = 'f98e7ca98a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('districts',
    sa.Column('state_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'state_id', name='uq_district_code_state')
    )
    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_districts_is_active'), ['is_active'], unique=False)
        batch_op.create_index('ix_districts_state_id', ['state_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.drop_index('ix_districts_state_id')
        batch_op.drop_index(batch_op.f('ix_districts_is_active'))

    op.drop_table('districts')
    # ### end Alembic commands ###
