"""add phase 2 catalog tables

Revision ID: bfea68e7409a
Revises: fb782d7bc09f
Create Date: 2026-07-30 22:34:40.278310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfea68e7409a'
down_revision = 'fb782d7bc09f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_types',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('activity_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_types_is_active'), ['is_active'], unique=False)

    op.create_table('cancellation_policies',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('refund_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('days_before_travel', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('cancellation_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cancellation_policies_is_active'), ['is_active'], unique=False)

    op.create_table('currencies',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('currencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_currencies_is_active'), ['is_active'], unique=False)

    op.create_table('hotel_categories',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('hotel_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hotel_categories_is_active'), ['is_active'], unique=False)

    op.create_table('meal_plans',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('meal_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_plans_is_active'), ['is_active'], unique=False)

    op.create_table('package_categories',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('package_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_package_categories_is_active'), ['is_active'], unique=False)

    op.create_table('payment_methods_master',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('payment_methods_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_methods_master_is_active'), ['is_active'], unique=False)

    op.create_table('seasons',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seasons_is_active'), ['is_active'], unique=False)

    op.create_table('tax_configurations',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_type', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('tax_configurations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_configurations_is_active'), ['is_active'], unique=False)

    op.create_table('vehicle_types',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('vehicle_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_types_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cities_is_active'))
        batch_op.drop_index(batch_op.f('ix_cities_state_id'))

    op.drop_table('cities')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('district_id', sa.CHAR(length=32), nullable=False),
    sa.Column('state_id', sa.CHAR(length=32), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('display_order', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=36), nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=36), nullable=True),
    sa.Column('version', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'state_id', name=op.f('uq_city_code_state'))
    )
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cities_state_id'), ['state_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cities_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('vehicle_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_types_is_active'))

    op.drop_table('vehicle_types')
    with op.batch_alter_table('tax_configurations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_configurations_is_active'))

    op.drop_table('tax_configurations')
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seasons_is_active'))

    op.drop_table('seasons')
    with op.batch_alter_table('payment_methods_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_methods_master_is_active'))

    op.drop_table('payment_methods_master')
    with op.batch_alter_table('package_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_package_categories_is_active'))

    op.drop_table('package_categories')
    with op.batch_alter_table('meal_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_plans_is_active'))

    op.drop_table('meal_plans')
    with op.batch_alter_table('hotel_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hotel_categories_is_active'))

    op.drop_table('hotel_categories')
    with op.batch_alter_table('currencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_currencies_is_active'))

    op.drop_table('currencies')
    with op.batch_alter_table('cancellation_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cancellation_policies_is_active'))

    op.drop_table('cancellation_policies')
    with op.batch_alter_table('activity_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_types_is_active'))

    op.drop_table('activity_types')
    # ### end Alembic commands ###
